apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-rating-service
  namespace: clahanstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-rating-service
  template:
    metadata:
      labels:
        app: review-rating-service
    spec:
      containers:
      - name: review-rating-service
        image: vignesh8386/review-rating-service:latest
        ports:
        - containerPort: 3012
        envFrom:
        - configMapRef:
            name: clahanstore-config
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi

---
apiVersion: v1
kind: Service 
metadata:
  name: review-rating-service
  namespace: clahanstore
spec:
  selector:
    app: review-rating-service
  ports:
  - protocol: TCP
    port: 3012
    targetPort: 3012
  type: LoadBalancer
