apiVersion: v1
kind: Secret
metadata:
  name: clahanstore-secrets
  namespace: clahanstore
type: Opaque
stringData:
  MONGO_URI_REVIEW: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/reviewdb"
  JWT_SECRET: "supersecretjwtkey_12345"